In [3]:
import numpy as np
import pandas as pd

In [4]:
dataset = pd.read_csv("Churn_Modelling.csv")

In [5]:
dataset

RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          225       NaN  Female   
2             3    15619304            Onio          629    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          619    France    Male   
7             8    15656148          Obinna          376   Germany     NaN   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

In [6]:
dataset.head(1)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

In [7]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography           True
Gender              True
Age                 True
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [8]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          1
Gender             1
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [9]:
# dataset.drop(["Geography"], axis=1)  # axis = 1 means deleting the column and axis=0 means deleting the row

In [10]:
dataset.head(1)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

In [11]:
# dataset[dataset["Geography"].isnull()].index.tolist()

In [12]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   
1          2    15647311      Hill          225       NaN  Female  41.0   
2          3    15619304      Onio          629    France  Female  42.0   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850     Spain  Female  43.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [13]:
# dataset.drop([1],axis=0, inplace=True)

In [14]:
dataset.head(3)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   
1          2    15647311      Hill          225       NaN  Female  41.0   
2          3    15619304      Onio          629    France  Female  42.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

In [15]:
dataset["Geography"].fillna(value="abc")

0        France
1           abc
2        France
3        France
4         Spain
5         Spain
6        France
7       Germany
8        France
9        France
10       France
11        Spain
12       France
13       France
14        Spain
15      Germany
16      Germany
17        Spain
18        Spain
19       France
20       France
21        Spain
22        Spain
23       France
24       France
25       France
26      Germany
27       France
28      Germany
29       France
         ...   
9970     France
9971     France
9972     France
9973     France
9974     France
9975    Germany
9976     France
9977     France
9978     France
9979     France
9980      Spain
9981    Germany
9982    Germany
9983     France
9984    Germany
9985     France
9986    Germany
9987      Spain
9988     France
9989      Spain
9990    Germany
9991     France
9992      Spain
9993     France
9994     France
9995     France
9996     France
9997     France
9998    Germany
9999     France
Name: Geography, Length:

In [16]:
dataset["Geography"].fillna(dataset["Geography"].mode()[0],inplace=True)
dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace=True)
dataset["Age"].fillna(dataset["Age"].mean(),inplace=True)

In [17]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender        Age  \
0          1    15634602  Hargrave          619    France  Female  42.000000   
1          2    15647311      Hill          225    France  Female  41.000000   
2          3    15619304      Onio          629    France  Female  42.000000   
3          4    15701354      Boni          699    France  Female  39.000000   
4          5    15737888  Mitchell          850     Spain  Female  43.000000   
5          6    15574012       Chu          645     Spain    Male  44.000000   
6          7    15592531  Bartlett          619    France    Male  50.000000   
7          8    15656148    Obinna          376   Germany    Male  38.924392   
8          9    15792365        He          501    France    Male  44.000000   
9         10    15592389        H?          684    France    Male  43.000000   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [18]:
df = pd.DataFrame([["a",20],["e",30],["b",40],["b",50],["c",60],["d",70]],columns = ["alphabets", "values"])

In [19]:
df

alphabets  values
0         a      20
1         e      30
2         b      40
3         b      50
4         c      60
5         d      70

In [20]:
df["values"].mean()

45.0

In [21]:
df["alphabets"].mode()

0    b
dtype: object

In [22]:
df["alphabets"].mode()[0]

'b'

In [23]:
dataset["Geography"].mode()[0]

'France'

In [24]:
#To give individual columns give them as a list like 3,5,7,9,10,11
#x = dataset.iloc[:,[3,5,7,9,10,11]]
x = dataset.iloc[:,3:13]
y = dataset.iloc[:,13]

In [25]:
x

CreditScore Geography  Gender        Age  Tenure    Balance  \
0             619    France  Female  42.000000       2       0.00   
1             225    France  Female  41.000000       1   83807.86   
2             629    France  Female  42.000000       8  159660.80   
3             699    France  Female  39.000000       1       0.00   
4             850     Spain  Female  43.000000       2  125510.82   
5             645     Spain    Male  44.000000       8  113755.78   
6             619    France    Male  50.000000       7       0.00   
7             376   Germany    Male  38.924392       4  115046.74   
8             501    France    Male  44.000000       4  142051.07   
9             684    France    Male  43.000000       2  134603.88   
10            528    France    Male  31.000000       6  134603.88   
11            497     Spain    Male  24.000000       3       0.00   
12            476    France  Female  34.000000      10       0.00   
13            549    France  Female  25.000000       5       0.00   
14            635     Spain  Female  35.000000       7       0.00   
15            616   Germany    Male  45.000000       3  143129.41   
16            653   Germany    Male  58.000000       1  132602.88   
17            549     Spain  Female  24.000000       9       0.00   
18            587     Spain    Male  45.000000       6       0.00   
19            726    France  Female  24.000000       6       0.00   
20            732    France    Male  41.000000       8       0.00   
21            636     Spain  Female  32.000000       8       0.00   
22            510     Spain  Female  38.000000       4       0.00   
23            669    France    Male  46.000000       3       0.00   
24            846    France  Female  38.000000       5       0.00   
25            577    France    Male  25.000000       3       0.00   
26            756   Germany    Male  36.000000       2  136815.64   
27            571    France    Male  44.000000       9       0.00   
28            574   Germany  Female  43.000000       3  141349.43   
29            411    France    Male  29.000000       0   59697.17   
...           ...       ...     ...        ...     ...        ...   
9970          518    France    Male  42.000000       7  151027.05   
9971          833    France  Female  34.000000       3  144751.81   
9972          758    France    Male  26.000000       4  155739.76   
9973          611    France    Male  27.000000       7       0.00   
9974          583    France    Male  33.000000       7  122531.86   
9975          610   Germany    Male  50.000000       1  113957.01   
9976          637    France  Female  33.000000       7  103377.81   
9977          683    France  Female  32.000000       9       0.00   
9978          774    France    Male  40.000000       9   93017.47   
9979          677    France  Female  58.000000       1   90022.85   
9980          741     Spain    Male  35.000000       6   74371.49   
9981          498   Germany    Male  42.000000       3  152039.70   
9982          655   Germany  Female  46.000000       7  137145.12   
9983          613    France    Male  40.000000       4       0.00   
9984          602   Germany    Male  35.000000       7   90602.42   
9985          659    France    Male  36.000000       6  123841.49   
9986          673   Germany    Male  47.000000       1  183579.54   
9987          606     Spain    Male  30.000000       8  180307.73   
9988          775    France    Male  30.000000       4       0.00   
9989          841     Spain    Male  28.000000       4       0.00   
9990          714   Germany    Male  33.000000       3   35016.60   
9991          597    France  Female  53.000000       4   88381.21   
9992          726     Spain    Male  36.000000       2       0.00   
9993          644    France    Male  28.000000       7  155060.41   
9994          800    France  Female  29.000000       2       0.00   
9995          771    France    Male  39.000000       5       0.00   
9996

In [26]:
y

0       1
1       0
2       1
3       0
4       0
5       1
6       0
7       1
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      1
17      0
18      0
19      0
20      0
21      0
22      1
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
9970    0
9971    0
9972    0
9973    0
9974    0
9975    1
9976    0
9977    0
9978    0
9979    0
9980    0
9981    1
9982    1
9983    0
9984    0
9985    0
9986    0
9987    0
9988    0
9989    0
9990    0
9991    1
9992    0
9993    0
9994    0
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [27]:
type(x)

pandas.core.frame.DataFrame

In [28]:
type(y)

pandas.core.series.Series

In [29]:
x = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

In [30]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [225, 'France', 'Female', ..., 0, 1, 112542.58],
       [629, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [31]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [32]:
type(x)

numpy.ndarray

In [33]:
dataset["Geography"].unique() # 100, 001, 010

array(['France', 'Spain', 'Germany'], dtype=object)

In [34]:
dataset["Gender"].unique() # 2

array(['Female', 'Male'], dtype=object)

In [35]:
x.shape   # 15, 13 done using column transformer

(10000, 10)

In [36]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [37]:
x[0]

array([619, 'France', 'Female', 42.0, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [38]:
# ct = ColumnTransformer([("oh",OneHotEncoder(),[passthecolumn number of categorical data])], remainder="passthrough")

In [39]:
ct = ColumnTransformer([("oh",OneHotEncoder(),[1,2])], remainder="passthrough")
x = ct.fit_transform(x)

In [40]:
x[0]

array([1.0, 0.0, 0.0, 1.0, 0.0, 619, 42.0, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [41]:
x.shape

(10000, 13)

age education occupation salary gender
education 5- PHD, BTech, MTech, None, Tenth
occupation 3- clerk, accountant, manager
gender- 3- male female transgender

a=ColumnTransformer[("oh", OneHotEncoder(), [1,2])], remainder="passthrough")
b=ct.fit_transform(x)
before= 5
after= 13

binary= PHD, BTech, MTech, None, Tenth
BTech- 10000
MTech- 01000
None- 00100
PHD- 00010
Tenth- 00001

Acountant- 100
Clerk- 010
Manager- 001

Female- 100
Male- 010
Transgender- 001

<2.0 version
Label Encoder- it actually converts textual data to integer encoding- 0, infinity
Onehot Encoder

In [42]:
df= dataset[['Gender','Geography','Age','Tenure']]
df

Gender Geography        Age  Tenure
0     Female    France  42.000000       2
1     Female    France  41.000000       1
2     Female    France  42.000000       8
3     Female    France  39.000000       1
4     Female     Spain  43.000000       2
5       Male     Spain  44.000000       8
6       Male    France  50.000000       7
7       Male   Germany  38.924392       4
8       Male    France  44.000000       4
9       Male    France  43.000000       2
10      Male    France  31.000000       6
11      Male     Spain  24.000000       3
12    Female    France  34.000000      10
13    Female    France  25.000000       5
14    Female     Spain  35.000000       7
15      Male   Germany  45.000000       3
16      Male   Germany  58.000000       1
17    Female     Spain  24.000000       9
18      Male     Spain  45.000000       6
19    Female    France  24.000000       6
20      Male    France  41.000000       8
21    Female     Spain  32.000000       8
22    Female     Spain  38.000000       4
23      Male    France  46.000000       3
24    Female    France  38.000000       5
25      Male    France  25.000000       3
26      Male   Germany  36.000000       2
27      Male    France  44.000000       9
28    Female   Germany  43.000000       3
29      Male    France  29.000000       0
...      ...       ...        ...     ...
9970    Male    France  42.000000       7
9971  Female    France  34.000000       3
9972    Male    France  26.000000       4
9973    Male    France  27.000000       7
9974    Male    France  33.000000       7
9975    Male   Germany  50.000000       1
9976  Female    France  33.000000       7
9977  Female    France  32.000000       9
9978    Male    France  40.000000       9
9979  Female    France  58.000000       1
9980    Male     Spain  35.000000       6
9981    Male   Germany  42.000000       3
9982  Female   Germany  46.000000       7
9983    Male    France  40.000000       4
9984    Male   Germany  35.000000       7
9985    Male    France  36.000000       6
9986    Male   Germany  47.000000       1
9987    Male     Spain  30.000000       8
9988    Male    France  30.000000       4
9989    Male     Spain  28.000000       4
9990    Male   Germany  33.000000       3
9991  Female    France  53.000000       4
9992    Male     Spain  36.000000       2
9993    Male    France  28.000000       7
9994  Female    France  29.000000       2
9995    Male    France  39.000000       5
9996    Male    France  35.000000      10
9997  Female    France  36.000000       7
9998    Male   Germany  42.000000       3
9999  Female    France  28.000000       4

[10000 rows x 4 columns]

In [43]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender']) #Female-0 and Male-1 (Alphabetical Order)
df['Geography']=le.fit_transform(df['Geography'])

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


In [44]:
df

Gender  Geography        Age  Tenure
0          0          0  42.000000       2
1          0          0  41.000000       1
2          0          0  42.000000       8
3          0          0  39.000000       1
4          0          2  43.000000       2
5          1          2  44.000000       8
6          1          0  50.000000       7
7          1          1  38.924392       4
8          1          0  44.000000       4
9          1          0  43.000000       2
10         1          0  31.000000       6
11         1          2  24.000000       3
12         0          0  34.000000      10
13         0          0  25.000000       5
14         0          2  35.000000       7
15         1          1  45.000000       3
16         1          1  58.000000       1
17         0          2  24.000000       9
18         1          2  45.000000       6
19         0          0  24.000000       6
20         1          0  41.000000       8
21         0          2  32.000000       8
22         0          2  38.000000       4
23         1          0  46.000000       3
24         0          0  38.000000       5
25         1          0  25.000000       3
26         1          1  36.000000       2
27         1          0  44.000000       9
28         0          1  43.000000       3
29         1          0  29.000000       0
...      ...        ...        ...     ...
9970       1          0  42.000000       7
9971       0          0  34.000000       3
9972       1          0  26.000000       4
9973       1          0  27.000000       7
9974       1          0  33.000000       7
9975       1          1  50.000000       1
9976       0          0  33.000000       7
9977       0          0  32.000000       9
9978       1          0  40.000000       9
9979       0          0  58.000000       1
9980       1          2  35.000000       6
9981       1          1  42.000000       3
9982       0          1  46.000000       7
9983       1          0  40.000000       4
9984       1          1  35.000000       7
9985       1          0  36.000000       6
9986       1          1  47.000000       1
9987       1          2  30.000000       8
9988       1          0  30.000000       4
9989       1          2  28.000000       4
9990       1          1  33.000000       3
9991       0          0  53.000000       4
9992       1          2  36.000000       2
9993       1          0  28.000000       7
9994       0          0  29.000000       2
9995       1          0  39.000000       5
9996       1          0  35.000000      10
9997       0          0  36.000000       7
9998       1          1  42.000000       3
9999       0          0  28.000000       4

[10000 rows x 4 columns]

In [45]:
x1=df.iloc[:,0:].values
x1

array([[ 0.,  0., 42.,  2.],
       [ 0.,  0., 41.,  1.],
       [ 0.,  0., 42.,  8.],
       ...,
       [ 0.,  0., 36.,  7.],
       [ 1.,  1., 42.,  3.],
       [ 0.,  0., 28.,  4.]])

spain, germany, france- categorical data
2, 1, 0- Integer data

In [46]:
x1.shape

(10000, 4)

In [47]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
z=one.fit_transform(x1[:,0:1]).toarray() #gender
w=one.fit_transform(x1[:,1:2]).toarray() #geography

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used

In [48]:
z

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [49]:
x1=np.delete(x1, (0,1),axis=1)
x1

array([[42.,  2.],
       [41.,  1.],
       [42.,  8.],
       ...,
       [36.,  7.],
       [42.,  3.],
       [28.,  4.]])

In [50]:
x1=np.concatenate((x1,w,z),axis=1)

In [51]:
x1.shape

(10000, 7)

x_train=questions - training
y_train=answers
x_test=questions in exam - test
y_test=key paper- calculate the accuracy

In [52]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [53]:
x.shape

(10000, 13)

In [54]:
x_train.shape

(8000, 13)

In [55]:
y_train.shape

(8000,)

In [56]:
x_test.shape

(2000, 13)

In [57]:
y_test.shape

(2000,)

In [58]:
x1=[1,2,3,4,5,6,7,8,9,10]
y1=[11,12,13,14,15,16,17,18,19,20]

In [59]:
#WITH RANDOM STATE
for i in range(5):
    x1_train, x1_test, y1_train, y1_test=train_test_split(x1,y1,test_size=0.2,random_state=0)
    print("x1_train",x1_train)
    print("x1_test",x1_test)
    print("y1_train",y1_train)
    print("y1_test",y1_test)
    
    print("************* iteration", i, "\n")

x1_train [5, 10, 2, 7, 8, 4, 1, 6]
x1_test [3, 9]
y1_train [15, 20, 12, 17, 18, 14, 11, 16]
y1_test [13, 19]
************* iteration 0 

x1_train [5, 10, 2, 7, 8, 4, 1, 6]
x1_test [3, 9]
y1_train [15, 20, 12, 17, 18, 14, 11, 16]
y1_test [13, 19]
************* iteration 1 

x1_train [5, 10, 2, 7, 8, 4, 1, 6]
x1_test [3, 9]
y1_train [15, 20, 12, 17, 18, 14, 11, 16]
y1_test [13, 19]
************* iteration 2 

x1_train [5, 10, 2, 7, 8, 4, 1, 6]
x1_test [3, 9]
y1_train [15, 20, 12, 17, 18, 14, 11, 16]
y1_test [13, 19]
************* iteration 3 

x1_train [5, 10, 2, 7, 8, 4, 1, 6]
x1_test [3, 9]
y1_train [15, 20, 12, 17, 18, 14, 11, 16]
y1_test [13, 19]
************* iteration 4 



In [60]:
#WITHOUT RANDOM STATE
for i in range(5):
    x1_train, x1_test, y1_train, y1_test=train_test_split(x1,y1,test_size=0.2)
    print("x1_train",x1_train)
    print("x1_test",x1_test)
    print("y1_train",y1_train)
    print("y1_test",y1_test)
    
    print("************* iteration", i, "\n")

x1_train [4, 9, 3, 6, 1, 7, 2, 8]
x1_test [5, 10]
y1_train [14, 19, 13, 16, 11, 17, 12, 18]
y1_test [15, 20]
************* iteration 0 

x1_train [5, 10, 7, 1, 6, 9, 8, 3]
x1_test [2, 4]
y1_train [15, 20, 17, 11, 16, 19, 18, 13]
y1_test [12, 14]
************* iteration 1 

x1_train [9, 2, 4, 6, 3, 1, 10, 7]
x1_test [8, 5]
y1_train [19, 12, 14, 16, 13, 11, 20, 17]
y1_test [18, 15]
************* iteration 2 

x1_train [1, 9, 3, 10, 2, 8, 5, 7]
x1_test [4, 6]
y1_train [11, 19, 13, 20, 12, 18, 15, 17]
y1_test [14, 16]
************* iteration 3 

x1_train [6, 7, 10, 8, 3, 5, 9, 2]
x1_test [1, 4]
y1_train [16, 17, 20, 18, 13, 15, 19, 12]
y1_test [11, 14]
************* iteration 4 



In [61]:
a=np.array([[1,2,3],[4,89,5],[200,300,10]])

In [62]:
a

array([[  1,   2,   3],
       [  4,  89,   5],
       [200, 300,  10]])

In [63]:
from sklearn.preprocessing import StandardScaler
p=StandardScaler()
a=p.fit_transform(a)

In [64]:
a #range -1 to 1

array([[-0.72315551, -1.02568612, -1.01904933],
       [-0.69093571, -0.33035086, -0.33968311],
       [ 1.41409121,  1.35603698,  1.35873244]])

x=x-mean/std deviation
Standardization on numerical data

In [65]:
df['Age']

0       42.000000
1       41.000000
2       42.000000
3       39.000000
4       43.000000
5       44.000000
6       50.000000
7       38.924392
8       44.000000
9       43.000000
10      31.000000
11      24.000000
12      34.000000
13      25.000000
14      35.000000
15      45.000000
16      58.000000
17      24.000000
18      45.000000
19      24.000000
20      41.000000
21      32.000000
22      38.000000
23      46.000000
24      38.000000
25      25.000000
26      36.000000
27      44.000000
28      43.000000
29      29.000000
          ...    
9970    42.000000
9971    34.000000
9972    26.000000
9973    27.000000
9974    33.000000
9975    50.000000
9976    33.000000
9977    32.000000
9978    40.000000
9979    58.000000
9980    35.000000
9981    42.000000
9982    46.000000
9983    40.000000
9984    35.000000
9985    36.000000
9986    47.000000
9987    30.000000
9988    30.000000
9989    28.000000
9990    33.000000
9991    53.000000
9992    36.000000
9993    28.000000
9994    29

In [66]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)

In [67]:
x_train

array([[-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [68]:
x_test=sc.fit_transform(x_test)

In [69]:
x_test

array([[-0.95692675,  1.62776996, -0.57427105, ...,  0.66011376,
         0.97628121,  1.62185911],
       [ 1.04501206, -0.61433742, -0.57427105, ...,  0.66011376,
        -1.02429504,  0.504204  ],
       [-0.95692675, -0.61433742,  1.74133801, ...,  0.66011376,
         0.97628121, -0.41865644],
       ...,
       [-0.95692675, -0.61433742,  1.74133801, ...,  0.66011376,
        -1.02429504,  0.72775202],
       [-0.95692675,  1.62776996, -0.57427105, ...,  0.66011376,
         0.97628121, -1.54162886],
       [-0.95692675,  1.62776996, -0.57427105, ...,  0.66011376,
        -1.02429504,  1.62356528]])

In [70]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 0.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

# After preprocessing, now build the ANN model...

### Steps to build ANN

1. Import necessary libraries
2. Initialize the model
3. Add Input Layer (no of nodes, weight, activation, learning rate)
4. Add Hidden Layers (no of nodes, weight, activation, learning rate)
5. Add Output Layer (no of nodes, weight, activation, learning rate)
6. Configure the learning processes:
   (optimizer=sqd/batch, error= mse/bce/cce, accuracy=[mse or accuracy])
7. Train the model- fit the model with xtrain and xtest
8. Test the model with test set (x_test)
9. Test the model with individual data (individual values)

In [74]:
from keras.models import Sequential #used to initialize the model
from keras.layers import Dense #used to add layers

In [75]:
import tensorflow as tf
import keras
print(tf.__version__)
print(keras.__version__)

1.14.0
2.3.1


https://colab.research.google.com/drive/1bMjxJxiTDlLwx8cb2IWjjxrj5KuI1PMZ?usp=sharing

Assignment- apply prediction to the bank dataset

In [2]:
import tensorflow as tf
import keras
print(tf.__version__)
print(keras.__version__)

1.14.0
2.3.1
